sudo: required

services:
  - docker

env:
  matrix:
    - DB=mysql:latest
    - DB=mariadb:latest

before_install:
  - docker run --name db_server -e MYSQL_ROOT_PASSWORD=my-secret-pw -d $DB

install:
  - pip install mechanize

script:
  # Build image
  - docker build -t phpmyadmin/phpmyadmin .
  # Test for single database
  - docker run --name testadmin -d --link db_server:db -p 9090:80 phpmyadmin/phpmyadmin
  - ./test-docker.sh testadmin 9090
  # Test for single database using env
  - docker run --name envadmin -d --link db_server:db2 -e PMA_HOST=db2 -p 6060:80 phpmyadmin/phpmyadmin
  - ./test-docker.sh envadmin 6060
  # Test for arbitrary database
  - docker run --name arbitraryadmin -d --link db_server:db3 -e PMA_ARBITRARY=1 -p 7070:80 phpmyadmin/phpmyadmin
  - ./test-docker.sh arbitraryadmin 7070 db3
  # Test for arbitrary database with user config
  - docker run --name userconfigadmin -d --link db_server:db3 -v `readlink -f ./config.test.inc.php`:/etc/phpmyadmin/config.user.inc.php -p 7080:80 phpmyadmin/phpmyadmin
  - ./test-docker.sh userconfigadmin 7080 db3
