FROM registry.cn-beijing.aliyuncs.com/partnersun/phpadmin:5.0.2-apache

WORKDIR /etc/apache2/sites-available


COPY ./000-default.conf .
RUN apt update && \
    apt install -y nano
    
WORKDIR /var/www
